name: Benchmarks (CodSpeed)

on:
  push:
    branches:
      - dev
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  benchmarks:
    name: Run benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Setup rust toolchain, cache and cargo-codspeed binary
        uses: moonrepo/setup-rust@ede6de059f8046a5e236c94046823e2af11ca670 # v1
        with:
          channel: stable
          cache-target: release
          bins: cargo-codspeed

      - name: Build the benchmark target(s)
        run: cargo codspeed build --features serde

      - name: Run the benchmarks
        uses: CodSpeedHQ/action@208425962c215de49ed713e18c4b9bde9bda5c52 # v4.10.2
        with:
          run: cargo codspeed run
          mode: instrumentation
