# Runs `cargo publish --dry-run` before another release

name: Check crate publishing works
on:
  pull_request:
    branches: [ release ]

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo_publish_dry_run:
    name: Publishing works
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install stable Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Get Cargo version
        id: cargo_version
        run: echo "::set-output name=version::$(cargo -V | tr -d ' ')"
        shell: bash

      - name: Download cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-${{ steps.cargo_version.outputs.version }}-${{ hashFiles('Cargo.toml') }}
          restore-keys: ${{ runner.os }}-${{ steps.cargo_version.outputs.version }}

      - name: Run `cargo publish --dry-run`
        run: cargo publish --dry-run
