# Automatically creates a tag for each commit to `main` so when we rebase
# changes on top of the upstream, we retain permanent references to each
# previous commit so they are not orphaned and eventually deleted.
name: Create permanent reference

on:
  push:
    branches:
      - "main"

jobs:
  create-permaref:
    runs-on: ubuntu-latest
    permissions:
      contents: "write"
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false

      - name: Get the permanent ref number
        id: get_version
        run: |
          # Enable pipefail so git command failures do not result in null versions downstream
          set -x

          echo "LAST_PERMA_NUMBER=$(\
            git ls-remote --tags --refs --sort="v:refname" \
            https://github.com/astral-sh/pubgrub.git | grep "tags/perma-" | tail -n1 | sed 's/.*\/perma-//' \
          )" >> $GITHUB_OUTPUT

      - name: Create and push the new tag
        env:
          GH_TOKEN: ${{ github.token }}
          LAST_PERMA_NUMBER: ${{ steps.get_version.outputs.LAST_PERMA_NUMBER }}
        run: |
          TAG="perma-$((LAST_PERMA_NUMBER + 1))"
          TAG_SHA="$(
            gh api --method POST "repos/${GITHUB_REPOSITORY}/git/tags" \
              -f tag="$TAG" \
              -f message='Automatically created on push to `main`' \
              -f object="$GITHUB_SHA" \
              -f type=commit \
              --jq .sha
          )"
          gh api --method POST "repos/${GITHUB_REPOSITORY}/git/refs" \
            -f ref="refs/tags/$TAG" \
            -f sha="$TAG_SHA"
